SENSOR_SEED = [
    {
        "tag": "M-101",
        "name": "Bomba de Resfriamento — Linha A",
        "area": "Setor 1 — Resfriamento",
        "nominal_voltage": 220.0,
        "nominal_current": 14.2,
        "nominal_rotation": 1755.0,
        "status": "ok",
        "baseline": {"v": 219.4, "i": 13.8, "t": 62.0, "rpm": 1752.0, "vib": 1.2},
    },
    {
        "tag": "M-102",
        "name": "Compressor Pneumático",
        "area": "Setor 1 — Resfriamento",
        "nominal_voltage": 220.0,
        "nominal_current": 21.5,
        "nominal_rotation": 1760.0,
        "status": "warn",
        "baseline": {"v": 218.9, "i": 23.1, "t": 84.0, "rpm": 1738.0, "vib": 3.4},
    },
    {
        "tag": "M-201",
        "name": "Esteira Transp. Linha B",
        "area": "Setor 2 — Linha de Produção",
        "nominal_voltage": 220.0,
        "nominal_current": 8.1,
        "nominal_rotation": 1745.0,
        "status": "ok",
        "baseline": {"v": 220.1, "i": 7.9, "t": 58.0, "rpm": 1745.0, "vib": 0.9},
    },
    {
        "tag": "M-202",
        "name": "Misturador Industrial",
        "area": "Setor 2 — Linha de Produção",
        "nominal_voltage": 220.0,
        "nominal_current": 28.0,
        "nominal_rotation": 1770.0,
        "status": "crit",
        "baseline": {"v": 217.2, "i": 31.4, "t": 96.0, "rpm": 1721.0, "vib": 5.8},
    },
    {
        "tag": "M-301",
        "name": "Exaustor Industrial",
        "area": "Setor 3 — Utilidades",
        "nominal_voltage": 220.0,
        "nominal_current": 11.3,
        "nominal_rotation": 1750.0,
        "status": "ok",
        "baseline": {"v": 220.4, "i": 11.0, "t": 60.0, "rpm": 1751.0, "vib": 1.0},
    },
    {
        "tag": "M-302",
        "name": "Bomba de Vácuo",
        "area": "Setor 3 — Utilidades",
        "nominal_voltage": 220.0,
        "nominal_current": 6.4,
        "nominal_rotation": 1740.0,
        # Desligado de propósito: é o caso que produz severidade `off`.
        "status": "off",
        "baseline": {"v": 0.0, "i": 0.0, "t": 28.0, "rpm": 0.0, "vib": 0.0},
    },
    {
        "tag": "M-303",
        "name": "Bomba de Recirc. d'Água",
        "area": "Setor 3 — Utilidades",
        "nominal_voltage": 220.0,
        "nominal_current": 9.1,
        "nominal_rotation": 1755.0,
        "status": "warn",
        "baseline": {"v": 219.0, "i": 10.2, "t": 78.0, "rpm": 1748.0, "vib": 2.6},
    },
]
